language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./_script/cibuild

script: ./_script/cibuild

env:
 global:
 - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
 apt:
  packages:
  - libcurl4-openssl-dev

cache: bundler

notifications:
  email: false
